name: Deploy Furnix Frontend

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set environment based on branch
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "TARGET_PATH=/var/www/furnixcrm/frontend-prod" >> $GITHUB_ENV
          else
            echo "TARGET_PATH=/var/www/furnixcrm/frontend-staging" >> $GITHUB_ENV
          fi

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "./*"
          target: "${{ env.TARGET_PATH }}"

      - name: Build & Deploy docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          timeout: 60m
          command_timeout: 60m
          script: |
            cd ${{ env.TARGET_PATH }}
            docker compose down || true
            docker compose build --no-cache
            docker compose up -d
            docker system prune -f
